name: Artifact

on: [push]
env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses:  action/Checkout@v2
      - name: Upload the artifact
        uses: action/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
  
